In [1]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import cross_validate , KFold
from sklearn.preprocessing import LabelEncoder

In [2]:
train_df = pd.read_csv("/Users/kato/Downloads/train (1).csv" , index_col="Id")
test_df = pd.read_csv("/Users/kato/Downloads/test (1).csv" , index_col="Id")

In [3]:
train_df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 1 to 1460
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   object
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   object
 5   Alley          91 non-null     object
 6   LotShape       1460 non-null   object
 7   LandContour    1460 non-null   object
 8   Utilities      1460 non-null   object
 9   LotConfig      1460 non-null   object
 10  LandSlope      1460 non-null   object
 11  Neighborhood   1460 non-null   object
 12  Condition1     1460 non-null   object
 13  Condition2     1460 non-null   object
 14  BldgType       1460 non-null   object
 15  HouseStyle     1460 non-null   object
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   object
 21  RoofMatl       1460 non-null   object
 22  Exterior1st    1460 non-null   object
 23  Exterior2nd    1460 non-null   object
 24  MasVnrType     588 non-null    object
 25  MasVnrArea     1452 non-null   float64
 26  ExterQual      1460 non-null   object
 27  ExterCond      1460 non-null   object
 28  Foundation     1460 non-null   object
 29  BsmtQual       1423 non-null   object
 30  BsmtCond       1423 non-null   object
 31  BsmtExposure   1422 non-null   object
 32  BsmtFinType1   1423 non-null   object
 33  BsmtFinSF1     1460 non-null   int64
 34  BsmtFinType2   1422 non-null   object
 35  BsmtFinSF2     1460 non-null   int64
 36  BsmtUnfSF      1460 non-null   int64
 37  TotalBsmtSF    1460 non-null   int64
 38  Heating        1460 non-null   object
 39  HeatingQC      1460 non-null   object
 40  CentralAir     1460 non-null   object
 41  Electrical     1459 non-null   object
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   object
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   object
 55  Fireplaces     1460 non-null   int64
 56  FireplaceQu    770 non-null    object
 57  GarageType     1379 non-null   object
 58  GarageYrBlt    1379 non-null   float64
 59  GarageFinish   1379 non-null   object
 60  GarageCars     1460 non-null   int64
 61  GarageArea     1460 non-null   int64
 62  GarageQual     1379 non-null   object
 63  GarageCond     1379 non-null   object
 64  PavedDrive     1460 non-null   object
 65  WoodDeckSF     1460 non-null   int64
 66  OpenPorchSF    1460 non-null   int64
 67  EnclosedPorch  1460 non-null   int64
 68  3SsnPorch      1460 non-null   int64
 69  ScreenPorch    1460 non-null   int64
 70  PoolArea       1460 non-null   int64
 71  PoolQC         7 non-null      object
 72  Fence          281 non-null    object
 73  MiscFeature    54 non-null     object
 74  MiscVal        1460 non-null   int64
 75  MoSold         1460 non-null   int64
 76  YrSold         1460 non-null   int64
 77  SaleType       1460 non-null   object
 78  SaleCondition  1460 non-null   object
 79  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(34), object(43)
memory usage: 923.9+ KB

In [5]:
train_df2 = train_df.select_dtypes(include="object")
train_df2.head()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
2,RL,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
3,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
4,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Abnorml
5,RL,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal

In [6]:
train_category = train_df2
for col in train_category:
    lbl = LabelEncoder()
    train_df2[col] = lbl.fit_transform(list(train_df2[col].values))

In [7]:
train_category

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,3,1,2,3,3,0,4,0,5,2,...,1,1,4,4,2,3,4,4,8,4
2,3,1,2,3,3,0,2,0,24,1,...,1,1,4,4,2,3,4,4,8,4
3,3,1,2,0,3,0,4,0,5,2,...,1,1,4,4,2,3,4,4,8,4
4,3,1,2,0,3,0,0,0,6,2,...,5,2,4,4,2,3,4,4,8,0
5,3,1,2,0,3,0,2,0,15,2,...,1,1,4,4,2,3,4,4,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,3,1,2,3,3,0,4,0,8,2,...,1,1,4,4,2,3,4,4,8,4
1457,3,1,2,3,3,0,4,0,14,2,...,1,2,4,4,2,3,2,4,8,4
1458,3,1,2,3,3,0,4,0,6,2,...,1,1,4,4,2,3,0,2,8,4
1459,3,1,2,3,3,0,4,0,12,2,...,1,2,4,4,2,3,4,4,8,4
1460,3,1,2,3,3,0,4,0,7,2,...,1,0,4,4,2,3,4,4,8,4

In [8]:
train_col_list = train_df2.columns.tolist()
train_col_list

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [9]:
train_df3 = train_df.drop(train_col_list, axis=1)
train_df3

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,0,61,0,0,0,0,0,2,2008,208500
2,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,298,0,0,0,0,0,0,5,2007,181500
3,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,0,42,0,0,0,0,0,9,2008,223500
4,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,0,35,272,0,0,0,0,2,2006,140000
5,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,192,84,0,0,0,0,0,12,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,62.0,7917,6,5,1999,2000,0.0,0,0,...,0,40,0,0,0,0,0,8,2007,175000
1457,20,85.0,13175,6,6,1978,1988,119.0,790,163,...,349,0,0,0,0,0,0,2,2010,210000
1458,70,66.0,9042,7,9,1941,2006,0.0,275,0,...,0,60,0,0,0,0,2500,5,2010,266500
1459,20,68.0,9717,5,6,1950,1996,0.0,49,1029,...,366,0,112,0,0,0,0,4,2010,142125
1460,20,75.0,9937,5,6,1965,1965,0.0,830,290,...,736,68,0,0,0,0,0,6,2008,147500

In [10]:
train_df = pd.merge(train_df3 , train_category , on="Id", how="left")
train_df.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,1,1,4,4,2,3,4,4,8,4
2,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,1,1,4,4,2,3,4,4,8,4
3,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,1,1,4,4,2,3,4,4,8,4
4,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,5,2,4,4,2,3,4,4,8,0
5,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,1,1,4,4,2,3,4,4,8,4

In [11]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 1 to 1460
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   LotFrontage    1201 non-null   float64
 2   LotArea        1460 non-null   int64
 3   OverallQual    1460 non-null   int64
 4   OverallCond    1460 non-null   int64
 5   YearBuilt      1460 non-null   int64
 6   YearRemodAdd   1460 non-null   int64
 7   MasVnrArea     1452 non-null   float64
 8   BsmtFinSF1     1460 non-null   int64
 9   BsmtFinSF2     1460 non-null   int64
 10  BsmtUnfSF      1460 non-null   int64
 11  TotalBsmtSF    1460 non-null   int64
 12  1stFlrSF       1460 non-null   int64
 13  2ndFlrSF       1460 non-null   int64
 14  LowQualFinSF   1460 non-null   int64
 15  GrLivArea      1460 non-null   int64
 16  BsmtFullBath   1460 non-null   int64
 17  BsmtHalfBath   1460 non-null   int64
 18  FullBath       1460 non-null   int64
 19  HalfBath       1460 non-null   int64
 20  BedroomAbvGr   1460 non-null   int64
 21  KitchenAbvGr   1460 non-null   int64
 22  TotRmsAbvGrd   1460 non-null   int64
 23  Fireplaces     1460 non-null   int64
 24  GarageYrBlt    1379 non-null   float64
 25  GarageCars     1460 non-null   int64
 26  GarageArea     1460 non-null   int64
 27  WoodDeckSF     1460 non-null   int64
 28  OpenPorchSF    1460 non-null   int64
 29  EnclosedPorch  1460 non-null   int64
 30  3SsnPorch      1460 non-null   int64
 31  ScreenPorch    1460 non-null   int64
 32  PoolArea       1460 non-null   int64
 33  MiscVal        1460 non-null   int64
 34  MoSold         1460 non-null   int64
 35  YrSold         1460 non-null   int64
 36  SalePrice      1460 non-null   int64
 37  MSZoning       1460 non-null   int64
 38  Street         1460 non-null   int64
 39  Alley          1460 non-null   int64
 40  LotShape       1460 non-null   int64
 41  LandContour    1460 non-null   int64
 42  Utilities      1460 non-null   int64
 43  LotConfig      1460 non-null   int64
 44  LandSlope      1460 non-null   int64
 45  Neighborhood   1460 non-null   int64
 46  Condition1     1460 non-null   int64
 47  Condition2     1460 non-null   int64
 48  BldgType       1460 non-null   int64
 49  HouseStyle     1460 non-null   int64
 50  RoofStyle      1460 non-null   int64
 51  RoofMatl       1460 non-null   int64
 52  Exterior1st    1460 non-null   int64
 53  Exterior2nd    1460 non-null   int64
 54  MasVnrType     1460 non-null   int64
 55  ExterQual      1460 non-null   int64
 56  ExterCond      1460 non-null   int64
 57  Foundation     1460 non-null   int64
 58  BsmtQual       1460 non-null   int64
 59  BsmtCond       1460 non-null   int64
 60  BsmtExposure   1460 non-null   int64
 61  BsmtFinType1   1460 non-null   int64
 62  BsmtFinType2   1460 non-null   int64
 63  Heating        1460 non-null   int64
 64  HeatingQC      1460 non-null   int64
 65  CentralAir     1460 non-null   int64
 66  Electrical     1460 non-null   int64
 67  KitchenQual    1460 non-null   int64
 68  Functional     1460 non-null   int64
 69  FireplaceQu    1460 non-null   int64
 70  GarageType     1460 non-null   int64
 71  GarageFinish   1460 non-null   int64
 72  GarageQual     1460 non-null   int64
 73  GarageCond     1460 non-null   int64
 74  PavedDrive     1460 non-null   int64
 75  PoolQC         1460 non-null   int64
 76  Fence          1460 non-null   int64
 77  MiscFeature    1460 non-null   int64
 78  SaleType       1460 non-null   int64
 79  SaleCondition  1460 non-null   int64
dtypes: float64(3), int64(77)
memory usage: 923.9 KB

In [12]:
test_df2 = test_df.select_dtypes(include="object")
test_df2.head()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1461,RH,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,...,Attchd,Unf,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal
1462,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,NaN,NaN,Gar2,WD,Normal
1463,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,Attchd,Fin,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal
1464,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1465,RL,Pave,NaN,IR1,HLS,AllPub,Inside,Gtl,StoneBr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal

In [13]:
test_category = test_df2
for col in test_category:
    lbl = LabelEncoder()
    test_df2[col] = lbl.fit_transform(list(test_df2[col].values))

In [14]:
test_category

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1461,2,1,2,3,3,0,4,0,12,1,...,1,2,3,4,2,2,2,3,8,4
1462,3,1,2,0,3,0,0,0,12,2,...,1,2,3,4,2,2,4,0,8,4
1463,3,1,2,0,3,0,4,0,8,2,...,1,0,3,4,2,2,2,3,8,4
1464,3,1,2,0,3,0,4,0,8,2,...,1,0,3,4,2,2,4,3,8,4
1465,3,1,2,0,1,0,4,0,22,2,...,1,1,3,4,2,2,4,3,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,4,1,2,3,3,0,4,0,10,2,...,6,3,4,5,2,2,4,3,8,4
2916,4,1,2,3,3,0,4,0,10,2,...,4,2,3,4,2,2,4,3,8,0
2917,3,1,2,3,3,0,4,0,11,2,...,5,2,3,4,2,2,4,3,8,0
2918,3,1,2,3,3,0,4,0,11,2,...,6,3,4,5,2,2,2,2,8,4
2919,3,1,2,3,3,0,4,1,11,2,...,1,0,3,4,2,2,4,3,8,4

In [15]:
test_col_list = test_df2.columns.tolist()
test_col_list

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [16]:
test_df3 = test_df.drop(test_col_list, axis=1)
test_df3

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,730.0,140,0,0,0,120,0,0,6,2010
1462,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,312.0,393,36,0,0,0,0,12500,6,2010
1463,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,482.0,212,34,0,0,0,0,0,3,2010
1464,60,78.0,9978,6,6,1998,1998,20.0,602.0,0.0,...,470.0,360,36,0,0,0,0,0,6,2010
1465,120,43.0,5005,8,5,1992,1992,0.0,263.0,0.0,...,506.0,0,82,0,0,144,0,0,1,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,21.0,1936,4,7,1970,1970,0.0,0.0,0.0,...,0.0,0,0,0,0,0,0,0,6,2006
2916,160,21.0,1894,4,5,1970,1970,0.0,252.0,0.0,...,286.0,0,24,0,0,0,0,0,4,2006
2917,20,160.0,20000,5,7,1960,1996,0.0,1224.0,0.0,...,576.0,474,0,0,0,0,0,0,9,2006
2918,85,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,...,0.0,80,32,0,0,0,0,700,7,2006
2919,60,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,...,650.0,190,48,0,0,0,0,0,11,2006

In [17]:
test_df = pd.merge(test_df3 , test_category , on="Id", how="left")
test_df.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,1,2,3,4,2,2,2,3,8,4
1462,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,1,2,3,4,2,2,4,0,8,4
1463,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,1,0,3,4,2,2,2,3,8,4
1464,60,78.0,9978,6,6,1998,1998,20.0,602.0,0.0,...,1,0,3,4,2,2,4,3,8,4
1465,120,43.0,5005,8,5,1992,1992,0.0,263.0,0.0,...,1,1,3,4,2,2,4,3,8,4

In [18]:
train_df.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,1,1,4,4,2,3,4,4,8,4
2,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,1,1,4,4,2,3,4,4,8,4
3,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,1,1,4,4,2,3,4,4,8,4
4,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,5,2,4,4,2,3,4,4,8,0
5,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,1,1,4,4,2,3,4,4,8,4

In [19]:
test_df.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,1,2,3,4,2,2,2,3,8,4
1462,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,1,2,3,4,2,2,4,0,8,4
1463,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,1,0,3,4,2,2,2,3,8,4
1464,60,78.0,9978,6,6,1998,1998,20.0,602.0,0.0,...,1,0,3,4,2,2,4,3,8,4
1465,120,43.0,5005,8,5,1992,1992,0.0,263.0,0.0,...,1,1,3,4,2,2,4,3,8,4

In [27]:
y = train_df["SalePrice"]
X = train_df.drop(columns=["SalePrice"])

In [28]:
X.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,1,1,4,4,2,3,4,4,8,4
2,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,1,1,4,4,2,3,4,4,8,4
3,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,1,1,4,4,2,3,4,4,8,4
4,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,5,2,4,4,2,3,4,4,8,0
5,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,1,1,4,4,2,3,4,4,8,4

In [29]:
y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

In [30]:
model = xgb.XGBRegressor(objective="reg:squarederror" , max_depth=10)
kf = KFold(n_splits=5 , shuffle=True)

In [32]:
score = cross_validate(model , X , y , cv=kf , scoring=["neg_mean_absolute_error"],return_estimator=True)
score

{'fit_time': array([0.45041323, 0.43038321, 0.43211532, 0.42845702, 0.41654015]),
 'score_time': array([0.00219488, 0.00254798, 0.00236893, 0.00233793, 0.00221086]),
 'estimator': [XGBRegressor(base_score=None, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bynode=None,
               colsample_bytree=None, early_stopping_rounds=None,
               enable_categorical=False, eval_metric=None, feature_types=None,
               gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
               interaction_constraints=None, learning_rate=None, max_bin=None,
               max_cat_threshold=None, max_cat_to_onehot=None,
               max_delta_step=None, max_depth=10, max_leaves=None,
               min_child_weight=None, missing=nan, monotone_constraints=None,
               n_estimators=100, n_jobs=None, num_parallel_tree=None,
               predictor=None, random_state=None, ...),
  XGBRegressor(base_score=None, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bynode=None,
               colsample_bytree=None, early_stopping_rounds=None,
               enable_categorical=False, eval_metric=None, feature_types=None,
               gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
               interaction_constraints=None, learning_rate=None, max_bin=None,
               max_cat_threshold=None, max_cat_to_onehot=None,
               max_delta_step=None, max_depth=10, max_leaves=None,
               min_child_weight=None, missing=nan, monotone_constraints=None,
               n_estimators=100, n_jobs=None, num_parallel_tree=None,
               predictor=None, random_state=None, ...),
  XGBRegressor(base_score=None, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bynode=None,
               colsample_bytree=None, early_stopping_rounds=None,
               enable_categorical=False, eval_metric=None, feature_types=None,
               gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
               interaction_constraints=None, learning_rate=None, max_bin=None,
               max_cat_threshold=None, max_cat_to_onehot=None,
               max_delta_step=None, max_depth=10, max_leaves=None,
               min_child_weight=None, missing=nan, monotone_constraints=None,
               n_estimators=100, n_jobs=None, num_parallel_tree=None,
               predictor=None, random_state=None, ...),
  XGBRegressor(base_score=None, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bynode=None,
               colsample_bytree=None, early_stopping_rounds=None,
               enable_categorical=False, eval_metric=None, feature_types=None,
               gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
               interaction_constraints=None, learning_rate=None, max_bin=None,
               max_cat_threshold=None, max_cat_to_onehot=None,
               max_delta_step=None, max_depth=10, max_leaves=None,
               min_child_weight=None, missing=nan, monotone_constraints=None,
               n_estimators=100, n_jobs=None, num_parallel_tree=None,
               predictor=None, random_state=None, ...),
  XGBRegressor(base_score=None, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bynode=None,
               colsample_bytree=None, early_stopping_rounds=None,
               enable_categorical=False, eval_metric=None, feature_types=None,
               gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
               interaction_constraints=None, learning_rate=None, max_bin=None,
               max_cat_threshold=None, max_cat_to_onehot=None,
               max_delta_step=None, max_depth=10, max_leaves=None,
               min_child_weight=None, missing=nan, monotone_constraints=None,
               n_estimators=100, n_jobs=None, num_parallel_tree=None,
               predictor=None, random_state=None, ...)],
 'test_neg_mean_absolute_error': array([-18227.28127676, -16617.71769317, -15900.88437768, -17868.35346211,
        -19614.99705693])}

In [35]:
mean_score = np.mean([score["estimator"][i].feature_importances_ for i in range(5)], axis=0)
mean_score

array([1.5615376e-04, 4.6420805e-04, 1.5147973e-03, 3.0791000e-01,
       2.3978672e-03, 3.2581142e-03, 2.5368982e-03, 7.7244808e-04,
       1.2375467e-02, 8.6354389e-04, 5.9744279e-04, 1.5295592e-02,
       6.4851888e-03, 7.2998712e-03, 2.9931876e-03, 4.1270532e-02,
       3.5658204e-03, 3.1197933e-04, 2.6844719e-02, 4.6804600e-04,
       1.9489934e-03, 1.0979185e-01, 2.9463419e-03, 3.7115910e-03,
       1.1385413e-03, 2.1045880e-01, 2.1460743e-03, 6.0567725e-04,
       1.1431625e-03, 7.5215683e-04, 4.7439188e-04, 6.3820323e-04,
       4.4781659e-04, 9.1804250e-04, 4.5839479e-04, 2.5892910e-04,
       1.2701939e-02, 0.0000000e+00, 8.4783994e-03, 1.2413384e-03,
       2.7000890e-03, 0.0000000e+00, 6.5385539e-04, 1.3341552e-02,
       2.6000096e-03, 1.2227688e-03, 1.1342532e-02, 4.4967630e-04,
       9.0573041e-04, 4.6080482e-04, 2.2918075e-04, 1.2831559e-03,
       5.2678084e-04, 6.8416283e-04, 4.8911395e-03, 1.6653395e-03,
       6.2171940e-04, 7.6546483e-02, 6.1188714e-04, 1.6889160e-03,
       1.3567831e-03, 7.8379957e-04, 8.5428916e-04, 4.6197110e-04,
       3.8811207e-02, 2.5920896e-04, 1.8328203e-02, 3.0551672e-03,
       8.0855412e-04, 5.5675046e-03, 1.9627695e-03, 4.2759551e-04,
       4.6049751e-04, 7.2481646e-04, 0.0000000e+00, 9.7854040e-04,
       5.5708828e-05, 1.9518277e-03, 3.0832388e-03], dtype=float32)

In [36]:
model.fit(X , y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=10, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [37]:
pred = model.predict(test_df)

In [38]:
pred

array([133736.56, 162438.27, 183977.94, ..., 152508.39, 107480.23,
       221185.11], dtype=float32)

In [43]:
pred = pd.DataFrame(pred)

In [44]:
pred.to_csv("/Users/kato/Desktop/0502pred.csv", index=False)